### ISSUE TITLE
Your example doesn't work

### ISSUE THREAD

**Issue by jazoom** [evanshortiss/expeditious-engine-redis#1]
`engine: require('expeditious-engine-redis')(redisOptions),`

I believe should be:

`engine: require('expeditious-engine-redis')( { redis: redisOptions } ),`

I had to go digging into the code to find out what was going on.

**Comment by evanshortiss** [comment]
@jazoom nice find will fix this 👍

**Comment by maheshyamsani** [comment]
> @jazoom nice find will fix this 👍

it will be good if you can update the read me with this, otherwise people like me won't understand the issue, unless I go in to your closed issues

**Comment by evanshortiss** [comment]
Done.

Remember, it's OSS. @maheshyamsani @jazoom, in the future, a PR is always welcome. This way _you_ can help too 😄

**Comment by jazoom** [comment]
@evanshortiss are you suggesting my report didn't help?

If I forked every project just to change one line I'd get nothing else done. Presumably project maintainers already have a local copy and it will just take 3 seconds to make the fix.

If I have to choose between spending 15 minutes to do the fork, fix, pull request dance and not posting the issue at all, I may just choose the latter. Especially since I didn't even end up using this library in the end.

**Comment by evanshortiss** [comment]
@jazoom not at all. Just that I'm happy to accept a PR if you spot something like this. I assume some folks don't PR because of fear it will be rejected or something, but maintainers are usually welcoming of it.

**Comment by evanshortiss** [comment]
Ah, and I should say "you can help too" was poor wording, I meant you can be a contributor and take some burden off a maintainer.

**Comment by jazoom** [comment]
No probs mate. Keep up the great work!
