### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by SimonSchick** [evanshortiss/expeditious-engine-redis#3]
Seeing that the main project supports TS, I don't get why this one doesn't. Can you add typings please?

**Comment by SimonSchick** [comment]
Basic port (minus deps):

```typescript
import { Callback, RedisClient } from 'redis';

export class RedisEngine {
  constructor(private client: RedisClient) {
  }

  public set(key: string, val: string, expire: number, callback: Callback<string>) {
    this.client.setex(
      key,
      Math.ceil(expire / 1000),
      val,
      callback,
    );
  }

  public get(key: string, callback: Callback<string>) {
    this.client.get(
      key,
      callback,
    );
  }

  public del(key: string, callback: Callback<number>) {
    this.client.del(
      key,
      callback,
    );
  }

  public ttl(key: string, callback: Callback<number | null>) {
    this.client.pttl(key, (err, ttl) => {
      if (err) {
        callback(err, null);
        return;
      }
      if (ttl && ttl < 0) {
        // Means there is no expire or key does not exist, we just return null
        callback(null, null);
        return;
      }
      callback(null, ttl);
    });
  }

  public flush(ns: string, callback: Callback<number | null>) {
    this.keys(ns, (err, keys) => {
      if (err) {
        callback(err, null);
        return;
      }

      const { client } = this;

      function del(idx = 0) {
        client.del(keys.slice(idx, idx + 10), (rErr, c) => {
          if (c !== 10) {
            callback(null, null);
            return;
          }
          if (rErr) {
            callback(rErr, null);
            return;
          }
          del(idx + 10);
        });
      }
      del(0);
    });
  }

  public keys(ns: string, callback: Callback<string[]>) {
    // Match all keys beginning with ns, e.g "items" => "items:*"
    this.client.keys(ns += ':*', callback);
  }
}

```

**Comment by evanshortiss** [comment]
@SimonSchick happy to add typings. Could you create a PR with this? You get the contribution 😄

**Comment by evanshortiss** [comment]
Oh, I see this is a full TS port. I am ok with that, just need to make sure it doesn't break existing compatibility

**Comment by SimonSchick** [comment]
This is the code I use locally to avoid #4 it's more or less equivalent, minus the use of async (using batch calls instead), verror (just passing the regular error).
That way I could shed 2 dependencies 😛

**Comment by SimonSchick** [comment]
That said, if this code passes your tests, it should be mostly fine, I didn't really change the interface functionality.

**Comment by evanshortiss** [comment]
Willing to drop both deps since `VError` is only used once IIRC and `async` can probably be replaced easily too. Still not sure if you want to make a PR or are you suggesting I do this?

**Comment by SimonSchick** [comment]
If you have the time I'd ask you to do it, I updated my OSX setup just now and it broke my dev env pretty badly.
I might be able to create a PR in a day or 2.

**Comment by evanshortiss** [comment]
Sure I'll give you the time to do it, if I don't see activity in a few days I'll pick it up 👍 

Appreciate it. Thanks!
