### ISSUE TITLE
Advice : strategy for cleaning

### ISSUE THREAD

**Issue by cyrilchapon** [evanshortiss/expeditious-engine-redis#5]
I'm willing to use this engine with express-expeditious.

I've got a kinda-static frontend app, I'm using node.js to compile (render) templates, and I'd like to perform response-caching to kill :

- Template rendering caching
- In memory (~redis) caching of my views

...in a single motion

The point is I'm deploying the whole stack on heroku, with heroku-redis addon.

The free tier of heroku-redis is limited to 10MB, and it's ok for my small app, but I'd like to keep it the *cleanest possible way*. So I'd basically would like to teardown the redis cache, either onStart or onStop of my app.

Is expeditious-engine-redis designed for this ? Is there any common / best practice for this of your knowledge ?

**Comment by evanshortiss** [comment]
@cyrilchapon sorry, I missed this. Did you get a solution. Could you call the `flush` function?
